[default.extend-words]

[files]
extend-exclude = [
  "CHANGELOG.md",
  "notebooks/*",
  "specs/changes/active/C002-v0.2.0-reliability/review-m1-2026-09-28.md",
  "specs/changes/active/C002-v0.2.0-reliability/evidence/m1-2026-09-28/spec/*.md",
  "specs/changes/active/C002-v0.2.0-reliability/evidence/m1-2026-09-28/standards/*.md",
  "specs/changes/completed/C002-v0.2.0-reliability/review-m1-2026-09-28.md",
  "specs/changes/completed/C002-v0.2.0-reliability/evidence/m1-2026-09-28/spec/*.md",
  "specs/changes/completed/C002-v0.2.0-reliability/evidence/m1-2026-09-28/standards/*.md",
]
