//! Command tree: the fixed machine representation of `specs/contracts/protocol.md` §2.

use clap::{Args, Parser, Subcommand};

#[derive(Debug, Parser)]
#[command(name = "sheltie", version, about = "A local workflow engine for coordinator agents", long_about = None)]
pub struct Cli {
    /// Emit a one-line JSON response envelope instead of human-readable text.
    #[arg(long, global = true)]
    pub json: bool,

    /// Management root. Defaults to SHELTIE_HOME, then ~/.sheltie.
    #[arg(long, global = true, value_name = "DIR")]
    pub home: Option<String>,

    /// Idempotency ID for write operations. Generated by the engine when omitted.
    #[arg(long, global = true, value_name = "UUID")]
    pub request_id: Option<String>,

    #[command(subcommand)]
    pub group: Group,
}

#[derive(Debug, Subcommand)]
pub enum Group {
    /// Manage sheltie itself.
    #[command(name = "self", subcommand)]
    SelfCmd(SelfCmd),
    /// Manage installed Workbooks.
    #[command(subcommand)]
    Workbook(WorkbookCmd),
    /// Create and inspect Works.
    #[command(subcommand)]
    Work(WorkCmd),
    /// Begin, submit, or fail an Attempt.
    #[command(subcommand)]
    Attempt(AttemptCmd),
    /// Approve a gate.
    #[command(subcommand)]
    Gate(GateCmd),
}

#[derive(Debug, Subcommand)]
pub enum SelfCmd {
    /// Install this binary into ~/.sheltie/bin and create the management root. Print PATH advice without changing shell configuration.
    Install,
    /// Download and verify a new version, then replace the binary atomically.
    Update {
        #[arg(long, value_name = "VERSION")]
        version: Option<String>,
    },
    /// Restore the previous binary version.
    Rollback,
    /// Remove bin/; --purge also clears managed data while retaining the root and lock.
    Uninstall {
        #[arg(long)]
        purge: bool,
        /// Skip confirmation for --purge.
        #[arg(long)]
        yes: bool,
    },
    /// Show version, platform, management root, and SCHEMA_VERSION.
    Version,
}

#[derive(Debug, Subcommand)]
pub enum WorkbookCmd {
    /// Validate and copy a Workbook directory into the management root.
    Add { dir: String },
    /// List installed Workbooks.
    List,
    /// Show the manifest, host resource declarations, and each Flow's nodes and edges.
    Show {
        /// `<id>` or `<id>@<version>`.
        spec: String,
    },
    /// Remove an installed version. Reject versions referenced by unfinished Works.
    Remove {
        /// Must be `<id>@<version>`.
        spec: String,
    },
    /// Recompute directory digests and compare them with stored records.
    Verify {
        /// Verify all installed versions when omitted.
        spec: Option<String>,
    },
}

#[derive(Debug, Subcommand)]
pub enum WorkCmd {
    /// Create a Work.
    Start(StartArgs),
    /// List Works.
    List,
    /// Show the status card.
    Status { work: String },
    /// Inspect explicitly selected final result references.
    Result {
        work: String,
        #[arg(long, allow_hyphen_values = true)]
        artifact: Option<String>,
        #[arg(long)]
        revision: Option<u64>,
    },
    /// Show facts: visits, attempts, failures, average duration, and incoming edges per node.
    Stats { work: String },
    /// Cancel a Work.
    Cancel { work: String },
}

#[derive(Debug, Args)]
pub struct StartArgs {
    /// `<id>` or `<id>@<version>`.
    #[arg(long)]
    pub workbook: String,
    #[arg(long)]
    pub flow: String,
    /// Defaults to the Flow ID when omitted.
    #[arg(long)]
    pub name: Option<String>,
    /// `k=v`; a value starting with `@` reads a file. May be repeated.
    #[arg(long = "input", value_name = "K=V")]
    pub inputs: Vec<String>,
}

#[derive(Debug, Subcommand)]
pub enum AttemptCmd {
    /// Enter a node and begin an Attempt, returning its brief.
    Begin {
        work: String,
        #[arg(long)]
        node: String,
    },
    /// Submit an Attempt.
    Submit {
        work: String,
        #[arg(long)]
        attempt: String,
        /// Summary text or `@file`.
        #[arg(long)]
        summary: String,
    },
    /// Mark an Attempt as failed.
    Fail {
        work: String,
        #[arg(long)]
        attempt: String,
        #[arg(long)]
        reason: String,
    },
    /// Revoke the current Attempt's submission qualification and obtain a new brief.
    Replace {
        work: String,
        #[arg(long)]
        attempt: String,
        /// Replacement reason or `@file`.
        #[arg(long)]
        reason: String,
    },
}

#[derive(Debug, Subcommand)]
pub enum GateCmd {
    /// Record human gate approval.
    Approve {
        work: String,
        #[arg(long)]
        node: String,
    },
}

/// Parse `k=v`; a value starting with `@` names a file. Runtime reads it only after replay lookup.
/// Return `(key, value source)`.
pub fn parse_input_arg(
    arg: &str,
) -> Result<(String, sheltie_runtime::request::InputValue), String> {
    let (key, value) = arg
        .split_once('=')
        .ok_or_else(|| format!("--input value {arg:?} must be k=v"))?;
    if key.is_empty() {
        return Err(format!("--input value {arg:?} is missing a key"));
    }
    let source = if let Some(path) = value.strip_prefix('@') {
        if path.is_empty() {
            return Err(format!("--input value {arg:?} requires a path after @"));
        }
        let abs = sheltie_runtime::request::lexical_abs(path).map_err(|error| error.to_string())?;
        sheltie_runtime::request::InputValue::AtFile { path: abs }
    } else {
        sheltie_runtime::request::InputValue::Literal {
            text: value.to_string(),
        }
    };
    Ok((key.to_string(), source))
}

/// Parse `<id>@<version>`. Without `@`, the version is `None`.
pub fn parse_workbook_spec(spec: &str) -> Result<(String, Option<String>), String> {
    if spec.is_empty() {
        return Err("Workbook reference must not be empty; use <id> or <id>@<version>".to_string());
    }
    match spec.split_once('@') {
        None => Ok((spec.to_string(), None)),
        Some((id, version)) => {
            if id.is_empty() || version.is_empty() {
                return Err(format!(
                    "Invalid Workbook reference {spec:?}; both sides of @ must be nonempty"
                ));
            }
            Ok((id.to_string(), Some(version.to_string())))
        }
    }
}

/// Value sources for `--summary` and `--reason`: `@` introduces a file path, read by runtime
/// after replay lookup; otherwise use the literal value.
pub fn parse_text_arg(value: &str) -> Result<sheltie_runtime::request::InputValue, String> {
    if let Some(path) = value.strip_prefix('@') {
        if path.is_empty() {
            return Err("A path is required after @".to_string());
        }
        let abs = sheltie_runtime::request::lexical_abs(path).map_err(|error| error.to_string())?;
        Ok(sheltie_runtime::request::InputValue::AtFile { path: abs })
    } else {
        Ok(sheltie_runtime::request::InputValue::Literal {
            text: value.to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Task: C002-T24
    #[test]
    fn input_file_arguments_are_lexical_and_do_not_probe_the_filesystem() {
        let missing = "/this/path/does/not/exist/sheltie-input";
        let (key, input) = parse_input_arg(&format!("topic=@{missing}")).unwrap();
        assert_eq!(key, "topic");
        assert_eq!(
            input,
            sheltie_runtime::request::InputValue::AtFile {
                path: missing.to_string()
            }
        );
        assert_eq!(
            parse_text_arg(&format!("@{missing}")).unwrap(),
            sheltie_runtime::request::InputValue::AtFile {
                path: missing.to_string()
            }
        );
    }
}
