import test from 'node:test';
import assert from 'node:assert/strict';
import { checkWorkbook } from '../lib/engine.mjs';
import { newWorkbook } from '../public/model.mjs';
const engine = process.env.SHELTIE_EDITOR_ENGINE;
if (!engine) throw new Error('A real trusted engine is required');
test('A real unreachable-node CLI error locates the problem while preserving technical output', async () => {
  const model = newWorkbook(); model.addNode('flows/default.toml');
  const result = await checkWorkbook(model.snapshot(), engine);
  console.log(JSON.stringify({ boundary: 'real-cli-disconnected-error', result }));
  assert.equal(result.ok, false);
  assert.deepEqual(result.engineError, { code: 'FLOW_INVALID', detail: { path: 'nodes[1].id', reason: 'Node step-2 is unreachable from entry step-1', rule: '3' }, message: 'Invalid Flow (rule 3, nodes[1].id): Node step-2 is unreachable from entry step-1' });
  assert.equal(result.error, result.engineError.message);
  assert.equal(result.process.code, 1); assert.equal(result.process.closed, true); assert.match(result.process.stdout, /FLOW_INVALID/);
});
import { syncTextPreviews, describeFailure } from '../public/presentation.mjs';
import { parse } from 'smol-toml';
test('Current name/title/instruction edits update exact file previews without replacing existing DOM objects', () => {
  const model = newWorkbook();
  const makePre = path => ({ dataset: { previewPath: path }, textContent: new TextDecoder().decode(model.snapshot().get(path)) });
  const manifestPre = makePre('workbook.toml'), flowPre = makePre('flows/default.toml');
  const focusedInput = { value: 'typing' }, expandedDetails = { open: true };
  const container = { focusedInput, expandedDetails, querySelectorAll: selector => { assert.equal(selector, '[data-preview-path]'); return [manifestPre, flowPre]; }, replaceChildren: () => { throw new Error('The properties panel must not be rebuilt'); } };
  model.edit('workbook.toml', model.manifest, 'name', 'preview-sync-check');
  const node = model.flow('flows/default.toml').nodes[0]; model.edit('flows/default.toml', node, 'title', 'current-title'); model.edit('flows/default.toml', node.instruction, 'text', '<img onerror=alert(1)>current-instructions');
  syncTextPreviews(model, container);
  const actualBytes = model.snapshot();
  assert.equal(manifestPre.textContent, new TextDecoder().decode(actualBytes.get('workbook.toml')));
  assert.equal(flowPre.textContent, new TextDecoder().decode(actualBytes.get('flows/default.toml')));
  assert.equal(parse(manifestPre.textContent).name, 'preview-sync-check'); assert.equal(parse(flowPre.textContent).nodes[0].title, 'current-title'); assert.equal(parse(flowPre.textContent).nodes[0].instruction.text, '<img onerror=alert(1)>current-instructions');
  assert.equal(container.focusedInput, focusedInput); assert.equal(focusedInput.value, 'typing'); assert.equal(container.expandedDetails, expandedDetails); assert.equal(expandedDetails.open, true);
});
test('Error presentation uses explicit code/rule/path, lists candidates without guessing the Flow, and keeps technical details separate', () => {
  const result = { error: 'fallback', engineError: { code: 'FLOW_INVALID', message: 'Invalid Flow', detail: { rule: '3', path: 'nodes[1].id', reason: 'Node step-2 is unreachable from entry step-1' } }, process: { stdout: 'technical escaped JSON', argv: ['/private/binary'] } };
  const issue = describeFailure(result, ['flows/default.toml', 'flows/other.toml']);
  assert.deepEqual(issue, { message: 'Invalid Flow', code: 'FLOW_INVALID', rule: '3', path: 'nodes[1].id', reason: 'Node step-2 is unreachable from entry step-1', next: 'Check the entry and explicit edges so every node is reachable; connecting nodes does not add input bindings.', fileNote: 'The engine did not identify an exact file. Open a candidate definition below and check the fields above.', candidates: ['workbook.toml', 'flows/default.toml', 'flows/other.toml'] });
  assert.doesNotMatch(JSON.stringify(issue), /private\/binary|technical escaped/);
  const unknown = describeFailure({ engineError: { code: 'UNKNOWN', message: 'literal <script>', detail: { path: 'unknown', reason: 'nodes[1].id does not authorize inferring rule 3' } } }, ['flows/default.toml']);
  assert.equal(unknown.rule, ''); assert.equal(unknown.next, 'Check the current file against the fields and reason above, then run the check again.'); assert.equal(unknown.message, 'literal <script>');
  const explicit = describeFailure({ engineError: { code: 'FLOW_INVALID', message: 'Rejected', detail: { file: 'flows/other.toml', rule: '1' } } }, ['flows/default.toml', 'flows/other.toml']); assert.deepEqual(explicit.candidates, ['flows/other.toml']); assert.equal(explicit.fileNote, 'File identified by the engine: flows/other.toml');
});
